#########################
# Groups
#########################

# Home
# ==============================
default_view:
 view: yes
 entities:
   - group.motion
   - group.switches
   - group.livingroom
   - group.garage
   - group.myclimate
Alarm:
  control: hidden
  name: Alarm
  view: yes
  entities:
    - group.alarmbadge
    - script.alarm_disarm
    - script.alarm_arm_home
    - input_boolean.alarm_override
alarmbadge:
  entities:
    - input_boolean.guest_mode
    - input_boolean.vacation_mode
sensor:
  name: sensors
  view: no
  entities: 
    - group.motion
office:
  name: Office
  view: yes
  entities: 
    - binary_sensor.linear_wapirz1_motion_sensor_sensor_2_0
    - sensor.linear_wapirz1_motion_sensor_alarm_level_2_1
    - sensor.linear_wapirz1_motion_sensor_alarm_type_2_0
    - sensor.linear_wapirz1_motion_sensor_sourcenodeid_2_2
    - sensor.linear_wapirz1_motion_sensor_temperature_2_1    
    - binary_sensor.linear_unknown_type2001_id0102_sensor_3_0
livingroom:
  name: Living Room
  view: yes
  entities:
    - switch.wemo_switch
    - binary_sensor.my_ecobee3_occupancy
    - camera.street_camera
garage:
  name: Garage
  entities:
    - camera.garage_camera
    - switch.ge_12722_onoff_relay_switch_switch_11_0
kitchen:
  name: kitchen
  view: yes
  entities:
    - switch.linear_unknown_type2005_id0503_switch_8_0
    - switch.hank_unknown_type0101_id0005_switch_10_0
    - sensor.hank_unknown_type0101_id0005_energy_10_0
    - sensor.hank_unknown_type0101_id0005_voltage_10_16
    - sensor.hank_unknown_type0101_id0005_power_10_8
myclimate:
  name: my climate
  icon: mdi:thermometer
  entities:
    - climate.my_ecobee3
    - sensor.my_ecobee3_humidity
    - sensor.my_ecobee3_temperature
weather:
  name: Weather
  view: yes
  entities:
    - sun.sun
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_summary
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_hourly_summary
global_settings:
  name: Global
  view: yes
  entities:
    - automation.nobody_home
    - switch.livingroom
    - switch.basement
# Switches
# ----------------------------------------
switches:
  name: switches
  entities:
    - switch.wemo_switch 
    - switch.linear_unknown_type2005_id0503_switch_8_0
    - switch.hank_unknown_type0101_id0005_switch_10_0 
    - sensor.hank_unknown_type0101_id0005_current_10_20
    - sensor.hank_unknown_type0101_id0005_energy_10_0
    - sensor.hank_unknown_type0101_id0005_power_10_8
    - sensor.hank_unknown_type0101_id0005_previous_reading_10_1
    - sensor.hank_unknown_type0101_id0005_previous_reading_10_9
    - sensor.hank_unknown_type0101_id0005_voltage_10_16
# Sensors
# ----------------------------------------
motion:
  name: motion
  entities:
    - binary_sensor.my_ecobee3_occupancy    
    - binary_sensor.linear_wapirz1_motion_sensor_sensor_2_0  
    - sensor.linear_unknown_type2001_id0102_alarm_level_3_1    
    - sensor.linear_unknown_type2001_id0102_alarm_level_4_1
    - sensor.linear_unknown_type2001_id0102_alarm_level_5_1
    - sensor.linear_unknown_type2001_id0102_alarm_level_6_1
    - sensor.linear_unknown_type2001_id0102_alarm_level_7_1
    - sensor.linear_wapirz1_motion_sensor_alarm_level_2_1
    - sensor.linear_wapirz1_motion_sensor_alarm_type_2_0
    - sensor.linear_wapirz1_motion_sensor_temperature_2_1
all_scripts:
  name: My Scripts
  view: yes
  entities:
    - script.restart_home_assistant
    - script.alarm_arm_away
    - script.alarm_arm_home
    - script.alarm_disarm
